app/urls.py
from django.urls import path
from . import views


app_name = 'app'

urlpatterns = [
    path('formpage/', views.FormView.as_view(),name="formpage"),
    path('doui/', views.ChoiceView.as_view(), name="doui"),
    path('kessai/', views.PrivacyView, name='kessai'),
]

pj_form/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]

app/models.py
from django.db import models

#モデルクラスを定義
class People(models.Model):
    Name = models.CharField(max_length=100)
    Furigana = models.CharField(max_length=100)
    Tell = models.IntegerField(blank=True, null=True)
    Mail = models.EmailField(max_length=100)
    Birthday = models.CharField(max_length=20)
    Adress = models.CharField(max_length=100)

app/forms.py
from django import forms
#モデルクラスを呼出
from .models import People
from django.core.exceptions import ValidationError
from django import forms
from django.contrib.admin import widgets
import os


widget_textinput = forms.TextInput(
    attrs={
        "class":"form-control",
    }
)

#フォームクラス作成
class Contact_Form(forms.ModelForm):

    class Meta():
        #①モデルクラスを指定
        model = People

        #②表示するモデルクラスのフィールドを定義
        fields = ('Name','Furigana','Tell','Mail','Birthday','Adress')


        #③表示ラベルを定義
        labels = {
            'Name':"名前　　",
            'Furigana':"フリガナ",
            'Tell':"電話番号",
            'Mail':"メール　",
            'Birthday':"生年月日",
            'Adress':"住所　　",
        }
        widget = {
            'Name': widget_textinput,
            'Furigana': widget_textinput,
            'Tell': widget_textinput,
            'Mail': widget_textinput,
            'Birthday': widget_textinput,
            'Adress': widget_textinput,
        }



class CheckeForm(forms.Form):
    selected_time = forms.fields.ChoiceField(
        choices = (
            ('','同意します'),
        ),
        label = '上記の内容に同意できる場合下記ボックスにチェックを入れてください',
        required = True,
        widget = forms.widgets.RadioSelect
    )

app/views.py
from django.shortcuts import render, redirect
from . import forms
from django.views.generic import TemplateView, FormView
from django.http import HttpResponseRedirect, HttpResponse
from . forms import Contact_Form, CheckeForm
from django.urls import reverse_lazy
from django.views import View



class FormView(TemplateView):

    #初期変数定義
    def __init__(self):
        self.params = {"Message":"情報を入力してください。",
                       "form":forms.Contact_Form(),
                       }

    #GET時の処理を記載
    def get(self,request):
        return render(request, "app/formpage.html",context=self.params)

    #POST時の処理を記載
    def post(self,request):
        if request.method == "POST":
            self.params["form"] = forms.Contact_Form(request.POST)

            #フォーム入力が有効な場合
            if self.params["form"].is_valid():
                #入力項目をデータベースに保存
                self.params["form"].save(commit=True)
                self.params["Message"] = "入力情報が送信されました。"
                return redirect(reverse_lazy('app:doui'))

        return render(request, "app/formpage.html",context=self.params)


class ChoiceView(View):
    def get(self, request):
        form = forms.CheckeForm()
        context = {
            'form': form
        }

        return render(request, 'app/doui.html', context)

def PrivacyView(request):
    return render(request, 'app/kessai.html')

app/templates/app/base.html
<!doctype HTML>
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          {% block head %}
            <a class="navbar-brand" href="/">登録</a>
          {% endblock %}
        </nav>
        <div class="container mt-4">
        {% block main %}
        <p>※コンテンツがありません。</p>
        {% endblock %}
        </div>
    </body>
</html>

app/templates/app/doui.html
{% extends "app/base.html" %}
{% load static %}

{% block head %}
<a class="navbar-brand" href="/">利用規約</a>
{% endblock %}

{% block main %}
<h1>利用規約</h1>
<div class="" style="border: 3px solid;">
  <p>
    同意書の内容<br>
    ,,,,,,,,<br>
    ,,,,,,,,<br>
    ,,,,,,,,,<br>
    hhhhhhhhh <br>
    ...........<br>
    ..........<br>
  </p>
</div>

{{form}}
<button onclick="location.href={% url 'app:kessai' %}"　class="btn btn-info">次へ</button>
{% endblock %}

app/templates/app/formpage.html
{% extends "app/base.html" %}

{% block head %}
<a class="navbar-brand" href="/">メンバー登録フォーム</a>

{% endblock %}

{% block main %}

<form method="POST" novalidate>
  {% csrf_token %}
  {% for field in form %}
  <div class="field">
    <p>
      <label>{{ field.label_tag }}</label>
      {{ field }}
    </p>

  </div>
  {% endfor %}
  <button type="submit" class="btn btn-info">送信</button>
</form>
<p>{{ message }}</p>

{% endblock %}

app/templates/app/kessai.html
{% extends "app/base.html" %}

{% block head %}
<a class="navbar-brand" href="/">登録</a>
{% endblock %}

{% block main %}

<h2>プラン選択</h2>
{{form}}

<h3>振込口座</h3>
<div class="" style="border: 3px solid;">
  <p>
    GMOあおぞらネット銀行
    金融機関コード 0310
    法人第二営業部
    支店コード102
    普通
    口座番号1072717
    カ)リバティー

  </p>
</div>
{% endblock %}